import multer from 'multer';
import path from 'path';
import fs from 'fs';

// Set storage engine
const storage = (category) => multer.diskStorage({
  destination(req, file, cb) {
    // Determine user ID (fallback to 'anonymous' if not joined by protect middleware)
    const userId = req.user ? req.user._id.toString() : 'anonymous';
    
    // Construct path: uploads/<category>/<userId>/
    const uploadPath = path.join('uploads', category, userId);
    
    // Create directory recursively if it doesn't exist
    try {
      if (!fs.existsSync(uploadPath)) {
        fs.mkdirSync(uploadPath, { recursive: true });
        console.log(`[Multer] Created directory: ${uploadPath}`);
      }
      cb(null, uploadPath);
    } catch (err) {
      console.error(`[Multer] Directory creation error: ${err.message}`);
      cb(err);
    }
  },
  filename(req, file, cb) {
    cb(
      null,
      `${file.fieldname}-${Date.now()}${path.extname(file.originalname)}`
    );
  },
});

// Check File Type
function checkFileType(file, cb) {
  // Allow common formats plus temp files generated by Flutter camera plugin
  const filetypes = /jpg|jpeg|png|mp4|mov|avi|mkv|aac|m4a|wav|mp3|mpeg|3gp|temp|tmp|webm/;
  // Check ext
  const extname = filetypes.test(path.extname(file.originalname).toLowerCase());
  // Check mime (Flutter sometimes sends application/octet-stream for temp files)
  const isVideoOrAudio = file.mimetype.startsWith('video/') || file.mimetype.startsWith('audio/') || file.mimetype.startsWith('image/');
  
  if (extname || isVideoOrAudio) {
    return cb(null, true);
  } else {
    cb('Error: Unsupported file type!');
  }
}

// Factory function to create upload middleware
const uploadMiddleware = (category = 'general') => {
  return multer({
    storage: storage(category),
    limits: { fileSize: 1024 * 1024 * 50 }, // 50MB limit
    fileFilter: function (req, file, cb) {
      checkFileType(file, cb);
    },
  });
};

export default uploadMiddleware;
